// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triolingo.Data;

#nullable disable

namespace Triolingo.Migrations
{
    [DbContext(typeof(TriolingoContext))]
    [Migration("20250126072127_CallingForSos")]
    partial class CallingForSos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Triolingo.Data.TriolingoUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ea731fc-9f88-42e7-a6cd-39d831ee31ef",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEINIUxGCnpXR91lD/31BZypixnqHhe7lxETi7tS4qw7ndO+HTDYDFxliDrhfesqQ1A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "03ef4514-ff5a-4586-82fc-6fe7e5381ea5",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5441),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5461),
                            LessonId = 0,
                            Name = "Japanese",
                            UpdatedBy = "System",
                            UserId = 0
                        },
                        new
                        {
                            LanguageId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5463),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5463),
                            LessonId = 0,
                            Name = "Chinese",
                            UpdatedBy = "System",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("LessonContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonOrder")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.ToTable("Lesson");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5642),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5642),
                            LanguageId = 1,
                            LessonContent = "あ is pronounced like 'ah!' like when you come to a realization. It also sounds like the 'a' in 'car'.\nい is pronounced like the 'ee' in 'eel'.\nう is pronounced like theu in 'UNO' the card game, or the number one in Spanish.\nえ is pronounced like the e in 'egg'\nお is pronounced like you're saying 'oh.' It also sounds like the o in 'origami'.",
                            LessonName = "Japanese Lesson 1",
                            LessonOrder = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            LessonId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5644),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5644),
                            LanguageId = 1,
                            LessonContent = "か is just the K sound plus あ, making a ka sound. It's pronounced like ka in 'karma.'\nき is just the K sound plus い, making a ki sound. It sounds ike the word 'key'\nく is just the K sound plus う, making a ku sound. It's pronounced 'coo' like both syllables of the word 'cuckoo'.\nけ is just the K sound plus え, making a ke sound. It's pronounced like ke in 'kelp.'\nこ is just the K sound plus お, making a ko sound. It's pronounced like co in 'coin'.",
                            LessonName = "Japanese Lesson 2",
                            LessonOrder = 2,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            LessonId = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5646),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5646),
                            LanguageId = 2,
                            LessonContent = "一 is the number 1 in chinese and it's pronouced 'yī'\n二 is the number 2 in chinese and it's pronouced 'èr'\n三 in the number 3 in chinese it's pronouced 'sān'\n四 in the number 4 in chinese it's pronouced 'sì'\n五 in the number 4 in chinese it's pronouced 'wǔ'\n",
                            LessonName = "Chinese Lesson 1",
                            LessonOrder = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            LessonId = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5647),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5648),
                            LanguageId = 2,
                            LessonContent = "六 is the number 6 in chinese and it's pronouced 'liù'\n七 is the number 7 in chinese and it's pronouced 'qī'\n八 in the number 8 in chinese it's pronouced 'bā'\n九 in the number 9 in chinese it's pronouced 'jiǔ'\n十 in the number 10 in chinese it's pronouced 'shí'\n",
                            LessonName = "Chinese Lesson 2",
                            LessonOrder = 2,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CorrectAnswer = "a",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5836),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5837),
                            QuestionText = "What is this hiragana? あ",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 2,
                            CorrectAnswer = "i",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5839),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5840),
                            QuestionText = "What is this hiragana? い",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 3,
                            CorrectAnswer = "u",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5842),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5843),
                            QuestionText = "What is this hiragana? う",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 4,
                            CorrectAnswer = "e",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5844),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5844),
                            QuestionText = "What is this hiragana? え",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 5,
                            CorrectAnswer = "o",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5846),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5846),
                            QuestionText = "What is this hiragana? お",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 6,
                            CorrectAnswer = "ka",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5847),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5848),
                            QuestionText = "What is this hiragana? か",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 7,
                            CorrectAnswer = "ki",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5849),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5850),
                            QuestionText = "What is this hiragana? き",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 8,
                            CorrectAnswer = "ku",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5851),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5851),
                            QuestionText = "What is this hiragana? く",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 9,
                            CorrectAnswer = "ke",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5853),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5853),
                            QuestionText = "What is this hiragana? け",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 10,
                            CorrectAnswer = "ko",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5854),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5855),
                            QuestionText = "What is this hiragana? こ",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("LevelDifficultly")
                        .HasColumnType("int");

                    b.Property<string>("QuizTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizId");

                    b.ToTable("Quiz");

                    b.HasData(
                        new
                        {
                            QuizId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5746),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5746),
                            LessonId = 1,
                            LevelDifficultly = 1,
                            QuizTitle = "Japanese Quiz 1",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            QuizId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5748),
                            DateUpdated = new DateTime(2025, 1, 26, 15, 21, 26, 550, DateTimeKind.Local).AddTicks(5748),
                            LessonId = 2,
                            LevelDifficultly = 2,
                            QuizTitle = "Japanese Quiz 2",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.QuizResult", b =>
                {
                    b.Property<int>("QuizResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizResultId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QuizResultId");

                    b.ToTable("QuizResult");
                });

            modelBuilder.Entity("Triolingo.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserProgress")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
