// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triolingo.Data;

#nullable disable

namespace Triolingo.Migrations
{
    [DbContext(typeof(TriolingoContext))]
    [Migration("20250125064633_SeedQuiz2")]
    partial class SeedQuiz2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Triolingo.Data.TriolingoUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c08bf51d-072f-431d-8fca-8e9c46a990e0",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIS+Osw2sAI1daFZAcl97O9KgV7MeXn8wfPYOAf6j5w/rqQHsuGEeowbL7EJj0VhHw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb694cd5-7618-4ec9-9a8d-16422d092023",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3276),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3294),
                            LessonId = 0,
                            Name = "Japanese",
                            UpdatedBy = "System",
                            UserId = 0
                        },
                        new
                        {
                            LanguageId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3296),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3296),
                            LessonId = 0,
                            Name = "Chinese",
                            UpdatedBy = "System",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("LessonContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LessonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonOrder")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.ToTable("Lesson");

                    b.HasData(
                        new
                        {
                            LessonId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3459),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3460),
                            LanguageId = 1,
                            LessonContent = "あ is pronounced like 'ah!' like when you come to a realization. It also sounds like the 'a' in 'car'.\nい is pronounced like the 'ee' in 'eel'.\nう is pronounced like theu in 'UNO' the card game, or the number one in Spanish.\nえ is pronounced like the e in 'egg'\nお is pronounced like you're saying 'oh.' It also sounds like the o in 'origami'.",
                            LessonName = "Japanese Lesson 1",
                            LessonOrder = 1,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            LessonId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3462),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3462),
                            LanguageId = 1,
                            LessonContent = "か is just the K sound plus あ, making a ka sound. It's pronounced like ka in 'karma.'\nき is just the K sound plus い, making a ki sound. It sounds ike the word 'key'\nく is just the K sound plus う, making a ku sound. It's pronounced 'coo' like both syllables of the word 'cuckoo'.\nけ is just the K sound plus え, making a ke sound. It's pronounced like ke in 'kelp.'\nこ is just the K sound plus お, making a ko sound. It's pronounced like co in 'coin'.",
                            LessonName = "Japanese Lesson 2",
                            LessonOrder = 2,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CorrectAnswer = "a",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3624),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3624),
                            QuestionText = "What is this hiragana? あ",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 2,
                            CorrectAnswer = "i",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3626),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3626),
                            QuestionText = "What is this hiragana? い",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 3,
                            CorrectAnswer = "u",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3627),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3627),
                            QuestionText = "What is this hiragana? う",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 4,
                            CorrectAnswer = "e",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3630),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3630),
                            QuestionText = "What is this hiragana? え",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 5,
                            CorrectAnswer = "o",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3633),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3634),
                            QuestionText = "What is this hiragana? お",
                            QuizId = 1,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 6,
                            CorrectAnswer = "ka",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3635),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3636),
                            QuestionText = "What is this hiragana? か",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 7,
                            CorrectAnswer = "ki",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3637),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3637),
                            QuestionText = "What is this hiragana? き",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 8,
                            CorrectAnswer = "ku",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3638),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3639),
                            QuestionText = "What is this hiragana? く",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 9,
                            CorrectAnswer = "ke",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3640),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3640),
                            QuestionText = "What is this hiragana? け",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        },
                        new
                        {
                            QuestionId = 10,
                            CorrectAnswer = "ko",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3642),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3642),
                            QuestionText = "What is this hiragana? こ",
                            QuizId = 2,
                            UpdatedBy = "System",
                            UserAnswer = ""
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("LevelDifficultly")
                        .HasColumnType("int");

                    b.Property<string>("QuizTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuizId");

                    b.ToTable("Quiz");

                    b.HasData(
                        new
                        {
                            QuizId = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3540),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3540),
                            LessonId = 1,
                            LevelDifficultly = 1,
                            QuizTitle = "Japanese Quiz 1",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            QuizId = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3542),
                            DateUpdated = new DateTime(2025, 1, 25, 14, 46, 32, 572, DateTimeKind.Local).AddTicks(3542),
                            LessonId = 2,
                            LevelDifficultly = 2,
                            QuizTitle = "Japanese Quiz 2",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Triolingo.Domain.QuizResult", b =>
                {
                    b.Property<int>("QuizResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizResultId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QuizResultId");

                    b.ToTable("QuizResult");
                });

            modelBuilder.Entity("Triolingo.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Triolingo.Data.TriolingoUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
